In [1]:
%pip install torch


Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://ppm.socom.mil/pypi/latest/simple, https://ppm.socom.mil/local-python-repo/latest/simple

[notice] A new release of pip is available: 23.3.2 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
print (torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

PyTorch tensor are created using torch.Tensor()

In [3]:
# scalar 

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,3,5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
# TENSOR Practice

TENSOR = torch.tensor([[[[1,2,3],
                         [3,6,9],
                         [2,3,5],
                         [1,2,4]]]])

In [17]:
TENSOR.ndim

4

In [18]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of randoms numbers and then adjust those random numbers to better represent that data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [26]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1826, 0.7564, 0.8023, 0.9465],
        [0.5147, 0.8341, 0.4619, 0.5191],
        [0.6379, 0.7655, 0.5274, 0.4126]])

In [27]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
random_image_size_tensor

tensor([[[0.9074, 0.2340, 0.2071],
         [0.2883, 0.2695, 0.5933],
         [0.0333, 0.7569, 0.3027],
         ...,
         [0.5769, 0.0537, 0.6327],
         [0.5275, 0.6784, 0.6616],
         [0.7042, 0.1389, 0.6861]],

        [[0.4568, 0.8433, 0.5304],
         [0.0205, 0.5809, 0.0191],
         [0.9420, 0.3740, 0.1030],
         ...,
         [0.2175, 0.1977, 0.4627],
         [0.6093, 0.5185, 0.9605],
         [0.3881, 0.0120, 0.4642]],

        [[0.6891, 0.8918, 0.0923],
         [0.2979, 0.6772, 0.0564],
         [0.9758, 0.5909, 0.9830],
         ...,
         [0.1381, 0.5798, 0.6942],
         [0.5078, 0.6333, 0.3818],
         [0.3374, 0.3729, 0.2395]],

        ...,

        [[0.9556, 0.8051, 0.4244],
         [0.9408, 0.7898, 0.8893],
         [0.9412, 0.6155, 0.3936],
         ...,
         [0.5841, 0.4371, 0.5759],
         [0.9592, 0.7295, 0.0056],
         [0.4191, 0.5190, 0.3972]],

        [[0.3404, 0.4755, 0.9330],
         [0.1041, 0.2093, 0.8428],
         [0.

### Zeros and ones


In [44]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors -like

In [43]:
# Use torch.range()

one_to_ten = torch.arange